#!/usr/bin/env python

import srt_tools.utils
import srt
import logging

log = logging.getLogger(__name__)

def main():
    args = srt_tools.utils.basic_parser().parse_args()
    logging.basicConfig(level=args.log_level)
    srt_tools.utils.set_basic_args(args)
    output = srt_tools.utils.compose_suggest_on_fail(
        args.input, strict=args.strict,
    )

    try:
        args.output.write(output)
    except (UnicodeEncodeError, TypeError):  # Python 2 fallback
        args.output.write(output.encode(args.encoding))


if __name__ == '__main__':
    main()
