#!/usr/bin/env python

import srt_tools.utils
import srt


def main():
    args = srt_tools.utils.basic_parser().parse_args()
    srt_tools.utils.set_basic_args(args)
    output = srt.compose(args.input, strict=args.strict)
    args.output.write(output)


if __name__ == '__main__':
    main()
