#!/usr/bin/env python

import re
import srt
import srt_tools.utils
import logging

log = logging.getLogger(__name__)

def strip_html_from_subs(subtitles):
    for subtitle in subtitles:
        subtitle_lines = subtitle.content.splitlines()
        stripped_subtitle_lines = (
            re.sub('<[^<]+?>', '', line) for line in subtitle_lines
        )
        subtitle.content = '\n'.join(stripped_subtitle_lines)
        yield subtitle


def main():
    args = srt_tools.utils.basic_parser().parse_args()
    logging.basicConfig(level=args.log_level)
    srt_tools.utils.set_basic_args(args)
    stripped_subs = strip_html_from_subs(args.input)
    output = srt_tools.utils.compose_suggest_on_fail(
        stripped_subs, args.strict,
    )

    try:
        args.output.write(output)
    except UnicodeEncodeError:  # Python 2 fallback
        args.output.write(output.encode(args.encoding))


if __name__ == '__main__':
    main()
